# Generated by Django 5.0.6 on 2026-01-30 17:18

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(db_index=True, max_length=10, verbose_name='Patente')),
                ('vtype', models.CharField(choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('COM', 'Comercial/Liviano')], max_length=4, verbose_name='Tipo')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('use', models.CharField(default='Particular', max_length=30, verbose_name='Uso')),
                ('fuel', models.CharField(blank=True, max_length=20, verbose_name='Combustible')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Titular')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['license_plate'],
            },
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('license_plate'), models.F('owner'), name='uniq_vehicle_owner_plate_ci'),
        ),
    ]
