# Generated by Django 5.0.6 on 2026-01-30 17:18

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('bullets', models.JSONField(blank=True, default=list)),
                ('vehicle_type', models.CharField(choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('COM', 'Comercial')], default='AUTO', max_length=5)),
                ('plan_type', models.CharField(choices=[('RC', 'Responsabilidad Civil'), ('TC', 'Terceros Completo'), ('TR', 'Todo Riesgo')], default='TR', max_length=2)),
                ('min_year', models.PositiveIntegerField(default=1995)),
                ('max_year', models.PositiveIntegerField(default=2100)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('franchise', models.CharField(blank=True, max_length=80)),
                ('coverages', models.TextField(blank=True, help_text='Lista de coberturas en markdown')),
                ('published_home', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('home_order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='uniq_product_code_lower'),
        ),
    ]
