# Generated by Django 5.0.6 on 2026-01-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_code_ci_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='home_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='coverages',
            field=models.TextField(blank=True, help_text='Lista de coberturas en markdown'),
        ),
        migrations.AlterField(
            model_name='product',
            name='plan_type',
            field=models.CharField(choices=[('RC', 'Responsabilidad Civil'), ('TC', 'Terceros Completo'), ('TR', 'Todo Riesgo')], default='TR', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='vehicle_type',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('COM', 'Comercial')], default='AUTO', max_length=5),
        ),
    ]
