# Generated by Django 5.0.6 on 2026-01-30 17:18

import quotes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=12, unique=True)),
                ('plan_code', models.CharField(blank=True, default='', max_length=50)),
                ('plan_name', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(max_length=32)),
                ('make', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
                ('version', models.CharField(max_length=120)),
                ('year', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=120)),
                ('has_garage', models.BooleanField()),
                ('is_zero_km', models.BooleanField()),
                ('usage', models.CharField(max_length=30)),
                ('has_gnc', models.BooleanField()),
                ('gnc_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('photo_front', models.ImageField(upload_to=quotes.models.quote_photo_upload_to)),
                ('photo_back', models.ImageField(upload_to=quotes.models.quote_photo_upload_to)),
                ('photo_right', models.ImageField(upload_to=quotes.models.quote_photo_upload_to)),
                ('photo_left', models.ImageField(upload_to=quotes.models.quote_photo_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ficha de cotización',
                'verbose_name_plural': 'Fichas de cotización',
                'ordering': ['-created_at'],
            },
        ),
    ]
