# Generated by Django 5.0.6 on 2026-01-30 17:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date_soft', models.DateField()),
                ('due_date_hard', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('status', models.CharField(choices=[('UNPAID', 'No pagado'), ('PAID', 'Pagado'), ('OVERDUE', 'Vencido')], db_index=True, default='UNPAID', max_length=10)),
                ('pricing_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_periods', to='policies.policy')),
            ],
            options={
                'verbose_name': 'Periodo de facturación',
                'verbose_name_plural': 'Periodos de facturación',
                'ordering': ['policy_id', 'period_start'],
                'unique_together': {('policy', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, help_text='Período AAAAMM (mes entre 01 y 12).', max_length=6, validators=[django.core.validators.RegexValidator(message='El período debe tener el formato AAAAMM y representar un mes válido.', regex='^(19|20)\\d{2}(0[1-9]|1[0-2])$')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(choices=[('PEN', 'Pendiente'), ('APR', 'Aprobado'), ('REJ', 'Rechazado')], default='PEN', max_length=3)),
                ('mp_preference_id', models.CharField(blank=True, max_length=80)),
                ('mp_payment_id', models.CharField(blank=True, max_length=80)),
                ('receipt_pdf', models.FileField(blank=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_state_change_at', models.DateTimeField(blank=True, null=True)),
                ('last_state_change_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('billing_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.billingperiod')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='policies.policy')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mercadopago', 'Mercado Pago')], max_length=40)),
                ('external_event_id', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.payment')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('concept', models.CharField(blank=True, max_length=120)),
                ('method', models.CharField(blank=True, max_length=30)),
                ('auth_code', models.CharField(blank=True, max_length=80)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('legacy_charge_id', models.IntegerField(blank=True, help_text='Legacy Charge PK preserved for audit after Charge removal. Charge no longer exists in runtime.', null=True)),
                ('legacy_charge_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Legacy Charge amount (if available) for historic receipts. Used for post-mortem reporting only.', max_digits=12, null=True)),
                ('legacy_charge_due_date', models.DateField(blank=True, help_text='Legacy Charge due date (if available) for historic receipts. Not part of the billing flow.', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='policies.policy')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'APR')), fields=('billing_period',), name='uniq_billing_period_approved'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentwebhookevent',
            unique_together={('provider', 'external_event_id')},
        ),
    ]
