from django.db import migrations, models
import django.db.models.deletion


def ensure_billingperiod_table_postgres(apps, schema_editor):
    """
    Historical safety net for PostgreSQL deployments where BillingPeriod table
    might be missing. Skip on non-PostgreSQL engines so local SQLite tests run.
    """
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
        CREATE TABLE IF NOT EXISTS payments_billingperiod (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            period_start date NOT NULL,
            period_end date NOT NULL,
            due_date_soft date NOT NULL,
            due_date_hard date NOT NULL,
            amount numeric(12,2) NOT NULL,
            currency varchar(3) NOT NULL DEFAULT 'ARS',
            status varchar(10) NOT NULL DEFAULT 'UNPAID',
            pricing_snapshot jsonb NULL,
            created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            policy_id bigint NOT NULL REFERENCES policies_policy(id) DEFERRABLE INITIALLY DEFERRED
        );
        """
    )
    schema_editor.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS payments_billingperiod_policy_period_start_uniq
        ON payments_billingperiod (policy_id, period_start);
        """
    )
    schema_editor.execute(
        """
        CREATE INDEX IF NOT EXISTS payments_billingperiod_status_idx
        ON payments_billingperiod (status);
        """
    )


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_paymentbatch"),
    ]

    operations = [
        migrations.RunPython(
            ensure_billingperiod_table_postgres,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="BillingNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("period_start", "Inicio de período de pago"),
                            ("soft_due_tomorrow", "Mañana vence (adelantado)"),
                            ("soft_due_today", "Último día de cobertura (adelantado)"),
                            ("no_coverage", "Sin cobertura (día posterior adelantado)"),
                            ("hard_due_today", "Último día real"),
                            ("hard_due_passed", "Vencida (día posterior real)"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("trigger_date", models.DateField(db_index=True)),
                ("sent_to", models.EmailField(blank=True, max_length=254)),
                ("subject", models.CharField(max_length=140)),
                ("body", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "billing_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="payments.billingperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación de cobro",
                "verbose_name_plural": "Notificaciones de cobro",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="billingnotification",
            constraint=models.UniqueConstraint(
                fields=("billing_period", "notification_type", "trigger_date"),
                name="uniq_billing_notification_per_day",
            ),
        ),
    ]
