# Generated by Django 5.0.6 on 2026-01-06 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_remove_payment_installment_requires_policy'),
        ('policies', '0009_policy_vehicle_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date_soft', models.DateField()),
                ('due_date_hard', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('UNPAID', 'No pagado'), ('PAID', 'Pagado'), ('OVERDUE', 'Vencido')], db_index=True, default='UNPAID', max_length=10)),
                ('pricing_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_periods', to='policies.policy')),
            ],
            options={
                'verbose_name': 'Periodo de facturación',
                'verbose_name_plural': 'Periodos de facturación',
                'ordering': ['policy_id', 'period_start'],
                'unique_together': {('policy', 'period_start')},
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='billing_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.billingperiod'),
        ),
    ]
