# Generated by Django on 2026-01-?? ???

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0016_billingperiod_payment_billing_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingperiod",
            name="currency",
            field=models.CharField(default="ARS", max_length=3),
            preserve_default=False,
        ),
    ]
