# Generated by Django on 2026-01-?? ???

from calendar import monthrange
from datetime import date

from django.db import migrations, models


def _backfill_billing_periods(apps, schema_editor):
    BillingPeriod = apps.get_model("payments", "BillingPeriod")
    Payment = apps.get_model("payments", "Payment")

    for payment in Payment.objects.filter(billing_period_id__isnull=True).select_related("policy"):
        period_code = getattr(payment, "period", "") or ""
        if not period_code or len(period_code) != 6 or not period_code.isdigit():
            continue
        year = int(period_code[:4])
        month = int(period_code[4:])
        try:
            period_start = date(year, month, 1)
        except ValueError:
            continue
        last_day = monthrange(year, month)[1]
        period_end = date(year, month, last_day)
        due_soft = period_end
        due_hard = period_end
        defaults = {
            "period_end": period_end,
            "due_date_soft": due_soft,
            "due_date_hard": due_hard,
            "amount": payment.amount or 0,
            "currency": "ARS",
            "status": "PAID" if payment.state == "APR" else "UNPAID",
        }
        billing_period, created = BillingPeriod.objects.get_or_create(
            policy_id=payment.policy_id,
            period_start=period_start,
            defaults=defaults,
        )
        if not created and payment.state == "APR" and billing_period.status != "PAID":
            billing_period.status = "PAID"
            billing_period.save(update_fields=["status"])
        payment.billing_period = billing_period
        payment.save(update_fields=["billing_period"])


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0017_add_billingperiod_currency"),
    ]

    operations = [
        migrations.RunPython(_backfill_billing_periods, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="payment",
            name="installment",
        ),
        migrations.AlterField(
            model_name="payment",
            name="billing_period",
            field=models.ForeignKey(
                on_delete=models.PROTECT,
                related_name="payments",
                to="payments.billingperiod",
                null=False,
                blank=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=["billing_period"],
                condition=models.Q(state="APR"),
                name="uniq_billing_period_approved",
            ),
        ),
    ]
