# Generated by Django 5.0.6 on 2026-01-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_require_billing_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingperiod',
            name='currency',
            field=models.CharField(default='ARS', max_length=3),
        ),
    ]
