# Generated by Django 5.0.6 on 2026-01-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField(blank=True, default='')),
                ('link', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiring_threshold_days', models.PositiveIntegerField(default=7)),
                ('client_expiration_offset_days', models.PositiveIntegerField(default=2)),
                ('default_term_months', models.PositiveIntegerField(default=3)),
                ('payment_window_days', models.PositiveIntegerField(default=5, help_text='Cantidad de días que dura la ventana de pago desde el inicio del ciclo mensual.')),
                ('payment_due_offset_days', models.PositiveIntegerField(default=0, help_text="Cantidad de días ANTES del último día de la ventana de pago que se muestra como 'vencimiento' al cliente. Debe ser menor que payment_window_days. Ej: window=10 y offset=3 => vencimiento visible = día 7.")),
                ('policy_adjustment_window_days', models.PositiveIntegerField(default=7, help_text='Cantidad de días antes del fin de la póliza en los que se considera el periodo de ajuste.')),
                ('payment_due_day_display', models.PositiveIntegerField(default=5, help_text='LEGACY: Día del mes comunicado al cliente como vencimiento (1-28/31).')),
                ('payment_due_day_real', models.PositiveIntegerField(default=7, help_text='LEGACY: Día del mes como corte real; debe ser >= display.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Ajustes de la app',
                'verbose_name_plural': 'Ajustes de la app',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(blank=True, default='+54 9 221 000 0000', max_length=50, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, default='hola@sancayetano.com', max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, default='Av. Ejemplo 1234, La Plata, Buenos Aires', max_length=255, verbose_name='Dirección')),
                ('map_embed_url', models.TextField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3283.798536911205!2d-58.381592984774424!3d-34.603738980460806!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMzTCsDM2JzEzLjQiUyA1OMKwMjInNTUuNyJX!5e0!3m2!1ses!2sar!4v1700000000000', help_text='Pega aquí el iframe src de Google Maps para mostrar la ubicación.', verbose_name='URL de iframe de mapa')),
                ('schedule', models.CharField(blank=True, default='Lun a Vie 9:00 a 18:00', max_length=120, verbose_name='Horario de atención')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contacto',
            },
        ),
    ]
