# Generated by Django 5.0.6 on 2026-01-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_singleton'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='payment_due_offset_days',
            field=models.PositiveIntegerField(default=0, help_text="Cantidad de días ANTES del último día de la ventana de pago que se muestra como 'vencimiento' al cliente. Debe ser menor que payment_window_days. Ej: window=10 y offset=3 => vencimiento visible = día 7."),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='payment_due_day_display',
            field=models.PositiveIntegerField(default=5, help_text='LEGACY: Día del mes comunicado al cliente como vencimiento (1-28/31).'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='payment_due_day_real',
            field=models.PositiveIntegerField(default=7, help_text='LEGACY: Día del mes como corte real; debe ser >= display.'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='payment_window_days',
            field=models.PositiveIntegerField(default=5, help_text='Cantidad de días que dura la ventana de pago desde el inicio del ciclo mensual.'),
        ),
    ]
