# Generated by Django 5.0.6 on 2026-01-30 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('premium', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('no_coverage', 'Sin cobertura'), ('expired', 'Vencida'), ('suspended', 'Suspendida'), ('cancelled', 'Cancelada'), ('inactive', 'Inactiva')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('claim_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('holder_dni', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to=settings.AUTH_USER_MODEL, verbose_name='Titular')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Póliza',
                'verbose_name_plural': 'Pólizas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(db_index=True, max_length=10, verbose_name='Patente')),
                ('make', models.CharField(max_length=80, verbose_name='Marca')),
                ('model', models.CharField(max_length=80, verbose_name='Modelo')),
                ('version', models.CharField(blank=True, max_length=80, verbose_name='Versión')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Ciudad')),
                ('has_garage', models.BooleanField(default=False)),
                ('is_zero_km', models.BooleanField(default=False)),
                ('usage', models.CharField(default='privado', max_length=30)),
                ('has_gnc', models.BooleanField(default=False)),
                ('gnc_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_vehicle', to='policies.policy')),
            ],
            options={
                'verbose_name': 'Vehículo de póliza',
                'verbose_name_plural': 'Vehículos de póliza',
            },
        ),
        migrations.CreateModel(
            name='PolicyInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Número de cuota dentro de la vigencia (1..N)')),
                ('period_start_date', models.DateField()),
                ('period_end_date', models.DateField(blank=True, null=True)),
                ('payment_window_start', models.DateField()),
                ('payment_window_end', models.DateField()),
                ('due_date_display', models.DateField()),
                ('due_date_real', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('near_due', 'Próximo a vencer'), ('paid', 'Pagado'), ('expired', 'Vencido')], default='pending', max_length=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='policies.policy')),
            ],
            options={
                'verbose_name': 'Cuota de póliza',
                'verbose_name_plural': 'Cuotas de póliza',
                'ordering': ['policy_id', 'sequence'],
                'unique_together': {('policy', 'sequence')},
            },
        ),
    ]
