# Generated by Codex on 2026-01-07
from django.db import migrations
from django.utils import timezone


def backfill_policy_vehicle_snapshots(apps, schema_editor):
    Policy = apps.get_model("policies", "Policy")
    PolicyVehicle = apps.get_model("policies", "PolicyVehicle")
    Vehicle = apps.get_model("vehicles", "Vehicle")

    policies = Policy.objects.filter(vehicle_id__isnull=False)
    for policy in policies.iterator():
        if PolicyVehicle.objects.filter(policy_id=policy.id).exists():
            continue
        try:
            vehicle = Vehicle.objects.get(pk=policy.vehicle_id)
        except Vehicle.DoesNotExist:
            continue
        PolicyVehicle.objects.create(
            policy_id=policy.id,
            plate=vehicle.license_plate,
            make=vehicle.brand,
            model=vehicle.model,
            version="",
            year=vehicle.year or timezone.now().year,
            city="",
            has_garage=False,
            is_zero_km=False,
            usage=vehicle.use or "privado",
            has_gnc=False,
            gnc_amount=None,
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0009_policy_vehicle_fk"),
        ("vehicles", "0004_alter_vehicle_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_policy_vehicle_snapshots, reverse_code=noop),
    ]
