# Generated by Django 5.0.6 on 2026-01-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0010_backfill_policyvehicle_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
