from calendar import monthrange
from datetime import date, timedelta
from decimal import Decimal
from django.core.management.base import BaseCommand

from accounts.models import User
from common.models import AppSettings
from policies.models import Policy
from policies.management.commands._vehicle_helpers import cleanup_owner_vehicles, ensure_policy_vehicle
from products.models import Product


def _shift_months(base_date: date, months: int) -> date:
    m = base_date.month - 1 + months
    year = base_date.year + m // 12
    month = m % 12 + 1
    day = min(base_date.day, monthrange(year, month)[1])
    return date(year, month, day)


class Command(BaseCommand):
    help = "Seed demo users and policies for local development/testing."

    def add_arguments(self, parser):
        parser.add_argument(
            "--reset",
            action="store_true",
            help="Borra polizas, vehiculos y usuarios demo antes de crear.",
        )
        parser.add_argument(
            "--reset-products",
            action="store_true",
            help="Tambien borra los productos antes de recrearlos.",
        )

    def handle(self, *args, **options):
        self.stdout.write("Creando datos de ejemplo...")
        user_data = self._user_data()
        demo_dnis = [u["dni"] for u in user_data]

        if options.get("reset"):
            self._reset_data(demo_dnis, options.get("reset_products", False))

        products = self._seed_products()
        users = self._seed_users(user_data)
        self._seed_policies(users, products)
        self.stdout.write(self.style.SUCCESS("Seed de polizas y usuarios completado."))

    def _product_data(self):
        """
        Asegura que existan algunos productos basicos.
        """
        return [
            dict(
                key="rc",
                code="AUTO-RC",
                name="Auto RC Basico",
                vehicle_type="AUTO",
                plan_type="RC",
                min_year=1995,
                max_year=2035,
                base_price=Decimal("12000"),
                franchise="-",
                coverages="- RC hasta X\n- Defensa civil",
                bullets=["Responsabilidad civil", "Defensa civil basica"],
            ),
            dict(
                key="tc",
                code="AUTO-TC",
                name="Auto Terceros Completo",
                vehicle_type="AUTO",
                plan_type="TC",
                min_year=2005,
                max_year=2035,
                base_price=Decimal("22000"),
                franchise="$50.000",
                coverages="- RC\n- Cristales\n- Granizo",
                bullets=["Cobertura de cristales", "Granizo", "Responsabilidad civil"],
            ),
            dict(
                key="tr",
                code="AUTO-TR",
                name="Auto Todo Riesgo",
                vehicle_type="AUTO",
                plan_type="TR",
                min_year=2015,
                max_year=2035,
                base_price=Decimal("42000"),
                franchise="$200.000",
                coverages="- Danos totales y parciales",
                bullets=["Todo riesgo", "Danos parciales", "Responsabilidad civil"],
            ),
        ]

    def _seed_products(self):
        product_data = self._product_data()
        product_map = {}
        for data in product_data:
            key = data.pop("key")
            product, _ = Product.objects.update_or_create(
                name=data["name"],
                defaults=data,
            )
            product_map[key] = product
        return product_map

    def _user_data(self):
        """
        Crea algunos usuarios clientes y un admin ligero.
        """
        return [
            dict(dni="10000001", first_name="Ana", last_name="Gonzalez", email="ana@example.com", phone="1130000001"),
            dict(dni="10000002", first_name="Bruno", last_name="Perez", email="bruno@example.com", phone="1130000002"),
            dict(dni="10000003", first_name="Carla", last_name="Diaz", email="carla@example.com", phone="1130000003"),
            dict(dni="20000000", first_name="Admin", last_name="Demo", email="admin@example.com", phone="1130000099", is_staff=True, is_superuser=True),
        ]

    def _seed_users(self, user_data):
        user_map = {}
        for data in user_data:
            dni = data.pop("dni")
            password = data.pop("password", "demo1234")
            user, created = User.objects.get_or_create(dni=dni, defaults=data)
            if created or not user.has_usable_password():
                user.set_password(password)
                user.save()
            user_map[dni] = user
        return user_map

    def _seed_policies(self, user_map, product_map):
        """
        Crea polizas con y sin usuario asignado, con vehiculos asociados.
        """
        today = date.today()
        price_every = max(1, getattr(AppSettings.get_solo(), "default_term_months", 3) or 3)
        price_target_next_start = today + timedelta(days=1)
        demo_price_start = _shift_months(price_target_next_start, -price_every)
        policies = [
            dict(
                number="SC-1001",
                user="10000001",
                product="rc",
                premium=Decimal("15500"),
                status="active",
                start=today - timedelta(days=30),
                end=today + timedelta(days=150),
                vehicle=dict(
                    plate="ABC123",
                    make="Toyota",
                    model="Etios",
                    version="XS",
                    year=2020,
                    city="CABA",
                    has_garage=True,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1002",
                user="10000002",
                product="tc",
                premium=Decimal("21500"),
                status="active",
                start=today - timedelta(days=90),
                end=today + timedelta(days=90),
                vehicle=dict(
                    plate="XYZ987",
                    make="Volkswagen",
                    model="Golf",
                    version="Comfortline",
                    year=2018,
                    city="La Plata",
                    has_garage=False,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=True,
                    gnc_amount=Decimal("60000"),
                ),
            ),
            dict(
                number="SC-1003",
                user="10000002",
                product="tr",
                premium=Decimal("33500"),
                status="expired",
                start=today - timedelta(days=420),
                end=today - timedelta(days=55),
                vehicle=dict(
                    plate="MNO456",
                    make="Ford",
                    model="Focus",
                    version="Titanium",
                    year=2016,
                    city="Rosario",
                    has_garage=True,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1004",
                user=None,
                product="rc",
                premium=Decimal("14200"),
                status="active",
                start=today - timedelta(days=10),
                end=today + timedelta(days=355),
                vehicle=dict(
                    plate="DEF234",
                    make="Renault",
                    model="Sandero",
                    version="Stepway",
                    year=2022,
                    city="Cordoba",
                    has_garage=False,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1005",
                user=None,
                product="tc",
                premium=Decimal("18900"),
                status="active",
                start=today - timedelta(days=5),
                end=today + timedelta(days=180),
                vehicle=dict(
                    plate="GHI789",
                    make="Chevrolet",
                    model="Onix",
                    version="LT",
                    year=2021,
                    city="Mendoza",
                    has_garage=True,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1006",
                user="10000001",
                product="rc",
                premium=Decimal("17200"),
                status="active",
                start=today - timedelta(days=120),
                end=today + timedelta(days=12),
                vehicle=dict(
                    plate="BPC321",
                    make="Fiat",
                    model="Cronos",
                    version="Premium",
                    year=2020,
                    city="Mar del Plata",
                    has_garage=True,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1007",
                user="10000002",
                product="tr",
                premium=Decimal("30500"),
                status="active",
                start=demo_price_start,
                end=_shift_months(demo_price_start, 6),
                vehicle=dict(
                    plate="PRX888",
                    make="Mercedes",
                    model="Clase A",
                    version="Edition",
                    year=2023,
                    city="Buenos Aires",
                    has_garage=True,
                    is_zero_km=True,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1008",
                user="10000003",
                product="rc",
                premium=Decimal("14950"),
                status="suspended",
                start=today - timedelta(days=250),
                end=today + timedelta(days=60),
                vehicle=dict(
                    plate="LMD452",
                    make="Peugeot",
                    model="208",
                    version="Active",
                    year=2019,
                    city="La Plata",
                    has_garage=False,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=True,
                    gnc_amount=Decimal("42000"),
                ),
            ),
            dict(
                number="SC-1009",
                user="10000001",
                product="tc",
                premium=Decimal("19800"),
                status="active",
                start=today - timedelta(days=45),
                end=today + timedelta(days=120),
                vehicle=dict(
                    plate="KJD112",
                    make="Honda",
                    model="Fit",
                    version="EXL",
                    year=2015,
                    city="CABA",
                    has_garage=False,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1010",
                user=None,
                product="rc",
                premium=Decimal("12700"),
                status="active",
                start=today - timedelta(days=60),
                end=today + timedelta(days=60),
                vehicle=dict(
                    plate="ASF884",
                    make="Suzuki",
                    model="Swift",
                    version="GL",
                    year=2014,
                    city="Bahía Blanca",
                    has_garage=False,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1011",
                user="10000002",
                product="tr",
                premium=Decimal("40200"),
                status="active",
                start=today - timedelta(days=5),
                end=today + timedelta(days=90),
                vehicle=dict(
                    plate="GRT556",
                    make="BMW",
                    model="X1",
                    version="SDrive",
                    year=2021,
                    city="Rosario",
                    has_garage=True,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1012",
                user="10000003",
                product="tc",
                premium=Decimal("18500"),
                status="cancelled",
                start=today - timedelta(days=200),
                end=today - timedelta(days=10),
                vehicle=dict(
                    plate="QWE321",
                    make="Renault",
                    model="Kwid",
                    version="Intense",
                    year=2019,
                    city="La Plata",
                    has_garage=False,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1013",
                user=None,
                product="tr",
                premium=Decimal("36200"),
                status="active",
                start=today - timedelta(days=180),
                end=today + timedelta(days=30),
                vehicle=dict(
                    plate="OJU998",
                    make="Audi",
                    model="A3",
                    version="Premium",
                    year=2018,
                    city="Mendoza",
                    has_garage=True,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1014",
                user="10000001",
                product="rc",
                premium=Decimal("19000"),
                status="active",
                start=today - timedelta(days=3),
                end=today + timedelta(days=360),
                vehicle=dict(
                    plate="KMN445",
                    make="Chevrolet",
                    model="Tracker",
                    version="LTZ",
                    year=2020,
                    city="Córdoba",
                    has_garage=False,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1015",
                user="10000002",
                product="tc",
                premium=Decimal("21000"),
                status="active",
                start=today - timedelta(days=4),
                end=today + timedelta(days=90),
                vehicle=dict(
                    plate="UDE221",
                    make="Volkswagen",
                    model="T-Cross",
                    version="Highline",
                    year=2022,
                    city="La Plata",
                    has_garage=True,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1016",
                user="10000003",
                product="rc",
                premium=Decimal("14300"),
                status="active",
                start=today - timedelta(days=5),
                end=today + timedelta(days=60),
                vehicle=dict(
                    plate="XYZ223",
                    make="Fiat",
                    model="Argo",
                    version="Precision",
                    year=2020,
                    city="Buenos Aires",
                    has_garage=True,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=True,
                    gnc_amount=Decimal("32000"),
                ),
            ),
            dict(
                number="SC-1017",
                user=None,
                product="tr",
                premium=Decimal("38800"),
                status="suspended",
                start=today - timedelta(days=15),
                end=today + timedelta(days=270),
                vehicle=dict(
                    plate="QAZ445",
                    make="Land Rover",
                    model="Defender",
                    version="110",
                    year=2024,
                    city="Tandil",
                    has_garage=True,
                    is_zero_km=True,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1018",
                user="10000001",
                product="rc",
                premium=Decimal("12900"),
                status="expired",
                start=today - timedelta(days=365),
                end=today - timedelta(days=30),
                vehicle=dict(
                    plate="TRW556",
                    make="Toyota",
                    model="Corolla",
                    version="Hybrid",
                    year=2016,
                    city="CABA",
                    has_garage=True,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1019",
                user="10000002",
                product="rc",
                premium=Decimal("16700"),
                status="active",
                start=today - timedelta(days=70),
                end=today + timedelta(days=4),
                vehicle=dict(
                    plate="JUN990",
                    make="Nissan",
                    model="Kicks",
                    version="SR",
                    year=2020,
                    city="La Plata",
                    has_garage=True,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1020",
                user=None,
                product="tc",
                premium=Decimal("17650"),
                status="active",
                start=today - timedelta(days=8),
                end=today + timedelta(days=80),
                vehicle=dict(
                    plate="ASH883",
                    make="Renault",
                    model="Logan",
                    version="Confort",
                    year=2021,
                    city="Córdoba",
                    has_garage=False,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1021",
                user="10000003",
                product="tr",
                premium=Decimal("41500"),
                status="active",
                start=today - timedelta(days=120),
                end=today + timedelta(days=10),
                vehicle=dict(
                    plate="RTY557",
                    make="Mazda",
                    model="CX-5",
                    version="Grand Touring",
                    year=2019,
                    city="Buenos Aires",
                    has_garage=True,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1022",
                user=None,
                product="rc",
                premium=Decimal("14200"),
                status="inactive",
                start=today - timedelta(days=200),
                end=today - timedelta(days=1),
                vehicle=dict(
                    plate="POI556",
                    make="Chevrolet",
                    model="Cruze",
                    version="LT",
                    year=2017,
                    city="Tucumán",
                    has_garage=False,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1023",
                user="10000001",
                product="tc",
                premium=Decimal("20500"),
                status="active",
                start=today - timedelta(days=30),
                end=today + timedelta(days=40),
                vehicle=dict(
                    plate="FUL994",
                    make="Citroën",
                    model="C4",
                    version="Feel",
                    year=2018,
                    city="San Luis",
                    has_garage=False,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=True,
                    gnc_amount=Decimal("28000"),
                ),
            ),
            dict(
                number="SC-1024",
                user="10000002",
                product="tr",
                premium=Decimal("45000"),
                status="active",
                start=today - timedelta(days=15),
                end=today + timedelta(days=210),
                vehicle=dict(
                    plate="KAZ232",
                    make="Porsche",
                    model="Macan",
                    version="S",
                    year=2024,
                    city="CABA",
                    has_garage=True,
                    is_zero_km=True,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1025",
                user=None,
                product="rc",
                premium=Decimal("11900"),
                status="active",
                start=today - timedelta(days=10),
                end=today + timedelta(days=90),
                vehicle=dict(
                    plate="DFT223",
                    make="Fiat",
                    model="Cronos",
                    version="Drive",
                    year=2019,
                    city="La Plata",
                    has_garage=False,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1026",
                user="10000003",
                product="tc",
                premium=Decimal("19300"),
                status="active",
                start=today - timedelta(days=130),
                end=today + timedelta(days=5),
                vehicle=dict(
                    plate="LMN883",
                    make="Peugeot",
                    model="3008",
                    version="Allure",
                    year=2020,
                    city="Mendoza",
                    has_garage=True,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1027",
                user=None,
                product="tr",
                premium=Decimal("38850"),
                status="cancelled",
                start=today - timedelta(days=260),
                end=today - timedelta(days=20),
                vehicle=dict(
                    plate="WER447",
                    make="Volvo",
                    model="XC40",
                    version="R-Design",
                    year=2018,
                    city="Rosario",
                    has_garage=True,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1028",
                user="10000001",
                product="rc",
                premium=Decimal("17250"),
                status="active",
                start=today - timedelta(days=75),
                end=today + timedelta(days=8),
                vehicle=dict(
                    plate="ZXM776",
                    make="Hyundai",
                    model="Creta",
                    version="Limited",
                    year=2021,
                    city="San Juan",
                    has_garage=False,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1029",
                user=None,
                product="tc",
                premium=Decimal("18100"),
                status="active",
                start=today - timedelta(days=2),
                end=today + timedelta(days=105),
                vehicle=dict(
                    plate="BND221",
                    make="Kia",
                    model="Rio",
                    version="EX",
                    year=2020,
                    city="San Fernando",
                    has_garage=True,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1030",
                user="10000002",
                product="tr",
                premium=Decimal("42000"),
                status="active",
                start=today - timedelta(days=40),
                end=today + timedelta(days=7),
                vehicle=dict(
                    plate="YUI778",
                    make="Jeep",
                    model="Compass",
                    version="Longitude",
                    year=2023,
                    city="Buenos Aires",
                    has_garage=True,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1031",
                user=None,
                product="rc",
                premium=Decimal("13400"),
                status="active",
                start=today - timedelta(days=7),
                end=today + timedelta(days=45),
                vehicle=dict(
                    plate="POI110",
                    make="Toyota",
                    model="Yaris",
                    version="S",
                    year=2021,
                    city="La Plata",
                    has_garage=False,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1032",
                user="10000003",
                product="tc",
                premium=Decimal("16200"),
                status="suspended",
                start=today - timedelta(days=50),
                end=today + timedelta(days=75),
                vehicle=dict(
                    plate="QWE001",
                    make="Ford",
                    model="Ecosport",
                    version="SE",
                    year=2019,
                    city="Mendoza",
                    has_garage=False,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1033",
                user="10000001",
                product="tr",
                premium=Decimal("39700"),
                status="active",
                start=today - timedelta(days=90),
                end=today + timedelta(days=20),
                vehicle=dict(
                    plate="OLO448",
                    make="Volvo",
                    model="XC60",
                    version="Momentum",
                    year=2020,
                    city="La Plata",
                    has_garage=True,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1034",
                user=None,
                product="rc",
                premium=Decimal("11200"),
                status="active",
                start=today - timedelta(days=5),
                end=today + timedelta(days=80),
                vehicle=dict(
                    plate="HMZ663",
                    make="Renault",
                    model="Stepway",
                    version="Iconic",
                    year=2018,
                    city="Salta",
                    has_garage=False,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1035",
                user="10000002",
                product="tc",
                premium=Decimal("19900"),
                status="inactive",
                start=today - timedelta(days=220),
                end=today - timedelta(days=5),
                vehicle=dict(
                    plate="JIK889",
                    make="Toyota",
                    model="Hilux",
                    version="SRV",
                    year=2017,
                    city="La Plata",
                    has_garage=True,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
            dict(
                number="SC-1036",
                user="10000003",
                product="tr",
                premium=Decimal("43200"),
                status="active",
                start=today - timedelta(days=12),
                end=today + timedelta(days=150),
                vehicle=dict(
                    plate="ZXK550",
                    make="Audi",
                    model="Q3",
                    version="Sportback",
                    year=2022,
                    city="Mar del Plata",
                    has_garage=True,
                    is_zero_km=False,
                    usage="privado",
                    has_gnc=False,
                    gnc_amount=None,
                ),
            ),
        ]

        for item in policies:
            product = product_map.get(item["product"])
            user = user_map.get(item["user"])
            policy_defaults = dict(
                user=user,
                product=product,
                premium=item["premium"],
                status=item["status"],
                start_date=item["start"],
                end_date=item["end"],
                holder_dni=getattr(user, "dni", None),
            )
            policy, _ = Policy.objects.update_or_create(
                number=item["number"],
                defaults=policy_defaults,
            )
            vehicle_data = item.get("vehicle")
            ensure_policy_vehicle(policy, vehicle_data)

    def _reset_data(self, demo_dnis, reset_products):
        """
        Borra datos existentes antes de sembrar de nuevo.
        """
        self.stdout.write("Limpiando datos previos...")
        owner_ids = list(User.objects.filter(dni__in=demo_dnis).values_list("id", flat=True))
        cleanup_owner_vehicles(owner_ids)
        Policy.objects.all().delete()
        User.objects.filter(dni__in=demo_dnis).delete()
        if reset_products:
            Product.objects.all().delete()
