# Generated by Django 5.0.6 on 2026-01-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_type', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_id', models.CharField(blank=True, max_length=64, null=True)),
                ('actor_repr', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(max_length=128)),
                ('entity_type', models.CharField(max_length=255)),
                ('entity_id', models.CharField(blank=True, max_length=128, null=True)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('client_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
